owncloud-docker/base

rootfs/etc/owncloud.d/50-memcached.sh
rootfs/etc/owncloud.d/55-redis.sh

related to https://github.com/owncloud/core/pull/31228
Phpredis 4.0 throws an Exception, when the redis server could not be reached.
Prior to this PR - the first `occ config:system:set memcache.distributed --value "\OC\Memcache\Redis"` would enable redis for successiv commands. 
However the redis host/port is not yet configured and ownCloud assumes `127.0.01` as host. Thus successive `occ` commands fail with a `RedisException`.
This PR turns the order of steps, to first define the host, and then enable locking.
The change for memcache was done, to keep the flow of steps consistent.
This error was found and fixed in `owncloud-ci/base` (https://github.com/owncloud-ci/base/commit/0dea59cef8b685dcfe0400231d93db7bf569a00d).

Fix errors with phpredis 4.0

---

rootfs/root/owncloud/objectstore.php

The configuration for `files_primary_s3` differs from the previous configuration for `objectstore`
```
'command.params' => [
'PathStyle' => ${OWNCLOUD_OBJECTSTORE_PATHSTYLE},
]
```
has been moved into the `options` key:
```
'options' => [
'use_path_style_endpoint' => true,
],
```
ref: https://github.com/owncloud/files_primary_s3/blob/master/tests/drone/scality.config.php

adjust configuration to be compatible with files_primary_s3

---

CHANGELOG.md
rootfs/etc/owncloud.d/20-config.sh
rootfs/etc/owncloud.d/45-php.sh
rootfs/etc/templates/config.php
rootfs/etc/templates/objectstore.php

If it's added too early the installation of ownCloud itself fails
because the required class from files_primary_s3 is missing, moving it
somewhere behind the `OWNCLOUD_APPS_INSTALL` processing resolves this
issue.

Load objectstore config later in the processing

---

CHANGELOG.md
rootfs/etc/owncloud.d/20-config.sh
rootfs/etc/owncloud.d/45-php.sh
rootfs/etc/templates/config.php
rootfs/etc/templates/objectstore.php

If it's added too early the installation of ownCloud itself fails
because the required class from files_primary_s3 is missing, moving it
somewhere behind the `OWNCLOUD_APPS_INSTALL` processing resolves this
issue.

[bionic] Load objectstore config later in the processing

---

CHANGELOG.md
rootfs/etc/owncloud.d/20-config.sh
rootfs/etc/owncloud.d/45-php.sh
rootfs/etc/templates/config.php
rootfs/etc/templates/objectstore.php

If it's added too early the installation of ownCloud itself fails
because the required class from files_primary_s3 is missing, moving it
somewhere behind the `OWNCLOUD_APPS_INSTALL` processing resolves this
issue.

[xenial] Load objectstore config later in the processing

---

CHANGELOG.md
rootfs/etc/owncloud.d/25-chown.sh

So far we are always rewriting the permissions to `www-data:www-data`
while the container gets built with `www-data:root`, the latter one is
the correct value for that.

[master] Fix chown to `www-data:root`, these are correct perms

---

CHANGELOG.md
rootfs/etc/owncloud.d/25-chown.sh

So far we are always rewriting the permissions to `www-data:www-data`
while the container gets built with `www-data:root`, the latter one is
the correct value for that.

[bionic] Fix chown to `www-data:root`, these are correct perms

---

CHANGELOG.md
rootfs/etc/owncloud.d/25-chown.sh

So far we are always rewriting the permissions to `www-data:www-data`
while the container gets built with `www-data:root`, the latter one is
the correct value for that.

[xenial] Fix chown to `www-data:root`, these are correct perms

---

rootfs/etc/entrypoint.d/98-overwrite.sh

Currently `APACHE_ACCESS_LOG` would fallback to `stderr`. We however should fallback to `/dev/stdout`.
This PR addresses the issue

Fix apache default output

---

rootfs/etc/templates/config.php

The config item mysql.utf8mb4 is a Boolean value, so the environment variable OWNCLOUD_MYSQL_UTF8MB4 must be interpreted as Boolean when being used to initialise mysql.utf8mb4.

Handle mysql.utf8mb4 override as Boolean value

---

rootfs/etc/owncloud.d/15-database.sh

Don't `wait-for-it` for clustered redis.

owncloud.d: don't wait for clustered redis

---

rootfs/etc/owncloud.d/15-database.sh

Signed-off-by: Alexander Trost <galexrt@googlemail.com>
(cherry picked from commit 91b3d60777cba26a1858f7103fb7cad5554aa316)

xenial: owncloud.d: don't wait for clustered redis

---

rootfs/etc/owncloud.d/15-database.sh

Signed-off-by: Alexander Trost <galexrt@googlemail.com>
(cherry picked from commit 91b3d60777cba26a1858f7103fb7cad5554aa316)

bionic: owncloud.d: don't wait for clustered redis

---

latest/overlay/etc/owncloud.d/15-database.sh
v16.04/overlay/etc/owncloud.d/15-database.sh
v18.04/overlay/etc/owncloud.d/15-database.sh
v18.10/overlay/etc/owncloud.d/15-database.sh
v19.04/overlay/etc/owncloud.d/15-database.sh
v19.10/overlay/etc/owncloud.d/15-database.sh

As one also could want to use a socket connection, we should only wait for redis connection if redis port is not set to 0.

Make startup script only wait for redis connection if port is not 0

---

v20.04/overlay/etc/php/7.4/mods-available/owncloud.ini

Fixes https://github.com/owncloud-docker/php/issues/35

default_socket_timeout to 3600

---

latest/overlay/etc/templates/config.php
v20.04/overlay/etc/templates/config.php

The `singleuser` config option expects a bool value, but right now we set it as string. As a result, every value set with `OWNCLOUD_SINGLEUSER` is added as string to the config.php and will be interpreted as `true` by the oC core bool check.
This fix ensures that a bool value is set in config.php. `OWNCLOUD_SINGLEUSER=true` will set `true` while every other value of the env var will fall back to `false` in the config.php.

fix: fix singleuser mode env var handling

---

.drone.star

Replace deprecated download.owncloud.org URL. As we execute just a quick test on this CI, I've switched to `owncloud-latest.tar.bz2` to avoid outdated oC versions used in CI.

fix: fix deprecated download urls in ci

---

latest/overlay/etc/owncloud.d/40-apps.sh
latest/overlay/etc/owncloud.d/50-apache.sh
latest/overlay/usr/bin/cronjob
v20.04/overlay/etc/owncloud.d/40-apps.sh
v20.04/overlay/etc/owncloud.d/50-apache.sh
v20.04/overlay/usr/bin/cronjob

Removes unnecessary `dpkg --compare-versions` version checks, as we don't build such old versions anymore.

chore: remove unnecessary version checks

---

latest/overlay/etc/owncloud.d/35-logging.sh
latest/overlay/usr/bin/occ
v20.04/overlay/etc/owncloud.d/35-logging.sh
v20.04/overlay/usr/bin/occ

The used tool gosu/su-exec creates a lot of noise in the security scanning (even if the CVE's are not applicable). As the same functionality can be achieved by OS  default tools this PR replaces gosu with setpriv.
```
usr/bin/su-exec (gobinary)
==========================
Total: 4 (UNKNOWN: 1, LOW: 0, MEDIUM: 3, HIGH: 0, CRITICAL: 0)
+--------------------------------+---------------------+----------+------------------------------------+-----------------------------------+----------------------------------------------+
|            LIBRARY             |  VULNERABILITY ID   | SEVERITY |         INSTALLED VERSION          |           FIXED VERSION           |                    TITLE                     |
+--------------------------------+---------------------+----------+---------------------- …
```

refactor: replace su-exec/gosu with setpriv

---

.drone.star
ENVIRONMENT.md
README.md
latest/overlay/etc/entrypoint.d/10-base.sh
latest/overlay/etc/templates/config.php
v20.04/overlay/etc/entrypoint.d/10-base.sh
v20.04/overlay/etc/templates/config.php

We need to figure out how to best communicate this change without breaking existing deployments.
Stop putting the `Host` from the request into the `trusted_domains` config.
I added a new environment variable `OWNCLOUD_TRUSTED_DOMAINS`, which can be used to set the trusted domains value:
E.g.: `OWNCLOUD_TRUSTED_DOMAINS=localhost,example.com`
If not set it will default to `localhost`
@xoxys, with this change setting the `OWNCLOUD_TRUSTED_DOMAINS` is required, otherwise the setup will not work properly.
How do we move on with this change or do you see another way?

breaking: add OWNCLOUD_TRUSTED_DOMAINS and don't rely on request headers

---

latest/overlay/etc/templates/owncloud.ini.tmpl
v20.04/overlay/etc/templates/owncloud.ini.tmpl

Right now setting `OWNCLOUD_SESSION_SAVE_HANDLER` to `redis` leads to the following error in the logs:
```
Updating htaccess config...
PHP:  syntax error, unexpected '=' in /etc/php/7.4/cli/conf.d/99-owncloud.ini on line 12
.htaccess has been updated
Writing apache config...
Enabling cron background...
PHP:  syntax error, unexpected '=' in /etc/php/7.4/cli/conf.d/99-owncloud.ini on line 12
```
This could be narrowed down to a wrong /etc/php/7.4/cli/conf.d/99-owncloud.ini:
```
session.save_handler = "redis"
session.save_path = "/mnt/data/sessions"redis.session.locking_enabled = 1
redis.session.lock_wait_time = 20000
redis.session.lock_retries = 750
```
This PR corrects the template to generate a correct ini file.

fix: add missing newline in the php redis config

---

latest/overlay/etc/templates/config.php
v20.04/overlay/etc/templates/config.php

Issue is described in https://github.com/owncloud/core/issues/40439#issuecomment-1304556277.
The fix changes `$domain` variable type from string to array if only `OWNCLOUD_DOMAIN` is provided.

fix: ensure trusted_domains is using an array

---

ENVIRONMENT.md
latest/overlay/etc/templates/owncloud.ini.tmpl
v20.04/overlay/etc/templates/owncloud.ini.tmpl

If `session.save_handler=redis` the default `session.save_path` is set automatically to the provided redis server address.

fix: set session.save_path accordingly while using redis

---

ENVIRONMENT.md

The documentation for `OWNCLOUD_REDIS_FAILOVER_MODE` was missing the possible values. This PR adds them.

fix: added description about possible OWNCLOUD_REDIS_FAILOVER_MODE values

---

latest/Dockerfile.amd64
latest/Dockerfile.arm32v7
latest/Dockerfile.arm64v8
v20.04/Dockerfile.amd64
v20.04/Dockerfile.arm32v7
v20.04/Dockerfile.arm64v8

Defining the default volume by `VOLUME ["/mnt/data"]` before creating the target directory resulted in an empty volume with base permissions of `root:root` and ignores the `mkdir` and `chown` commands defined later in the Dockerfile. This PR corrects the order of the `RUN` and `VOLUME` statement to properly create the volume's target directory structure and base permissions. This change only affects new setups with an empty volume. Bind mounts or existing (non-empty) Docker volumes added during deployment remain unaffected.

fix: fix wrong volume target directory setup

---

latest/overlay/etc/owncloud.d/15-database.sh
v20.04/overlay/etc/owncloud.d/15-database.sh

For a Redis host with TLS enabled, the hostname is expected to be prefixed with `tls://` in the configuration. However, that prefix should be omitted when checking for liveness of the Redis socket.

Support TLS enabled Redis host

---

ENVIRONMENT.md
latest/overlay/etc/templates/config.php
v20.04/overlay/etc/templates/config.php

This PR adds support for `file_storage.save_version_metadata` so it can be set via the environment variable `OWNCLOUD_SAVE_VERSION_METADATA`.

feat: add support for file_storage.save_version_metadata

---

ENVIRONMENT.md
v20.04/overlay/etc/entrypoint.d/85-others.sh
v20.04/overlay/etc/templates/config.php

Docker users can now specify via the environment
OWNCLOUD_INDICATORS_OF_COMPROMISE_SCANNER_CONFIRMATION=EXECUTED_ON_ALL_NODES
as an alternative to
occ c:s:s indicators-of-compromise-scanner.confirmation --value EXECUTED_ON_ALL_NODES

build: add ioc env variable to overwrite.php

---

v20.04/overlay/etc/templates/config.php

When trying to setup a password-protected Redis cluster configuration by defining following in the docker-compose file:
Following is generated in config.php:
which obviously fails.
As explained by @xoxys, `OWNCLOUD_REDIS_HOST` always defaults to redis so we need to extend the condition considering the case where `OWNCLOUD_REDIS_SEEDS` is (not) set.
Additionally, we need to add the condition for the redis cluster password.

fix: adjust condition for redis cluster

---

.drone.star

We may as well bump this Ubuntu that is used in some drone CI steps to 22.04

chore: use Ubuntu 22.04 in drone CI

---

v20.04/Dockerfile.multiarch
v22.04/Dockerfile.multiarch

The web updater is disabled via the config within the docker image creation.
There is absolutly no need to ship this code.

fix: remove unused web updater
